l_simp_chinese:
 #DELETE:
 #pm_disabled_gin
 #pm_disabled_elastics
 #pm_masticators
 #pm_rubber_bands
 #pm_luxury_clothes
 #Agriculture Buildings
 pm_primary: "主要"
 pmg_secondary_building_rye_farm: "次要"
 pmg_secondary_building_wheat_farm: "次要"
 pmg_secondary_building_rice_farm: "次要"
 pmg_secondary_building_maize_farm: "次要"
 pmg_secondary_building_millet_farm: "次要"
 pm_no_secondary: "维持单一作物"
 pm_potatoes: "马铃薯"
 pm_vineyards: "葡萄园"
 pm_vineyards_building_maize_farm: "葡萄园"
 pm_apple_orchards: "苹果园"
 pm_citrus_orchards: "柑橘园"
 pm_fig_orchards: "无花果园"
 pm_fig_orchards_building_rice_farm: "无花果园"
 pm_mulberry_groves: "桑树林"
 pmg_automation: "自动化"
 pmg_automation_building_food_industry: "自动化"
 pmg_automation_building_textile_mills: "自动化"
 pmg_automation_building_furniture_manufacturies: "自动化"
 pmg_automation_building_tooling_workshops: "自动化"
 pmg_automation_building_paper_mills: "自动化"
 pmg_automation_building_steel_mills: "自动化"
 pmg_automation_building_motor_industry: "自动化"
 pmg_automation_building_automotive_industry: "$pmg_automation$"
 pm_civilian_priority: "民用优先"
 pm_military_priority: "军用优先"
 #Textile Mills
 pm_craftsman_sewing: "工匠缝纫"
 pm_sewing_machines: "缝纫机"
 pm_electric_sewing_machines: "电动缝纫机"
 pm_traditional_looms: "传统织机"
 pm_mechanized_looms: "机械化织机"
 pm_automatic_power_looms: "自动化动力织机"
 #Glassworks
 pm_leaded_glass: "含铅玻璃"
 pm_manual_glassblowing: "手工吹制玻璃"
 #Chemical Plants
 pm_leblanc_process: "勒布朗法"
 pm_no_explosives_production: "优先肥料生产"
 pm_ammonia-soda_process: "氨碱法"
 pm_vacuum_evaporation: "真空蒸发"
 pm_brine_electrolysis: "氯碱法"
 pmg_fertilizer_production: "肥料生产"
 pm_no_artificial_fertilizers: "无人工肥"
 pm_artificial_fertilizers: "人工肥"
 pm_improved_fertilizer: "改良化肥"
 pm_nitrogen_fixation: "固氮法"
 pm_dyes_production: "染料生产"
 pm_no_synthetic_dyes: "无合成染料"
 pmg_synthetic_dyes: "合成染料"
 pm_silk_production: "丝绸生产"
 pm_no_artificial_fibers: "优先染料生产"
 pm_rayon: "尼龙"
 #Foundries
 pm_steamworks: "蒸汽作业"
 pm_no_artillery_production: "优先轻武器生产"
 pm_artillery_production: "火炮生产"
 #Motor Industries
 pmg_automobile_production: "汽车生产"
 pm_automobile_production: "汽车生产"
 pm_mass_automobile_production: "大规模生产"
