l_polish:
 #DELETE:
 #pm_disabled_gin
 #pm_disabled_elastics
 #pm_masticators
 #pm_rubber_bands
 #pm_luxury_clothes
 #Agriculture Buildings
 pm_primary: "Podstawowa"
 pmg_secondary_building_rye_farm: "Drugorzędna"
 pmg_secondary_building_wheat_farm: "Drugorzędna"
 pmg_secondary_building_rice_farm: "Drugorzędna"
 pmg_secondary_building_maize_farm: "Drugorzędna"
 pmg_secondary_building_millet_farm: "Drugorzędna"
 pm_no_secondary: "Uprawa jednolita"
 pm_potatoes: "Ziemniaki"
 pm_vineyards: "Winnice"
 pm_vineyards_building_maize_farm: "Winnice"
 pm_apple_orchards: "Sady jabłoniowe"
 pm_citrus_orchards: "Sady cytrusowe"
 pm_fig_orchards: "Sady figowe"
 pm_fig_orchards_building_rice_farm: "Sady figowe"
 pm_mulberry_groves: "Zagajniki morwowe"
 pmg_automation: "Automatyzacja"
 pmg_automation_building_food_industry: "Automatyzacja"
 pmg_automation_building_textile_mills: "Automatyzacja"
 pmg_automation_building_furniture_manufacturies: "Automatyzacja"
 pmg_automation_building_tooling_workshops: "Automatyzacja"
 pmg_automation_building_paper_mills: "Automatyzacja"
 pmg_automation_building_steel_mills: "Automatyzacja"
 pmg_automation_building_motor_industry: "Automatyzacja"
 pm_civilian_priority: "Priorytet cywilny"
 pm_military_priority: "Priorytet wojskowy"
 #Textile Mills
 pm_craftsman_sewing: "Krawiectwo rzemieślnicze"
 pm_sewing_machines: "Maszyny do szycia"
 pm_electric_sewing_machines: "Elektryczne maszyny do szycia"
 pm_traditional_looms: "Krosna tradycyjne"
 pm_mechanized_looms: "Krosna mechaniczne"
 pm_automatic_power_looms: "Automatyczne krosna mechaniczne"
 #Glassworks
 pm_leaded_glass: "Szkło ołowiowe"
 pm_manual_glassblowing: "Tradycyjne dmuchanie szkła"
 #Chemical Plants
 pm_leblanc_process: "Metoda Leblanca"
 pm_no_explosives_production: "Priorytetowa produkcja nawozu"
 pm_ammonia-soda_process: "Proces amoniakowo-sodowy"
 pm_vacuum_evaporation: "Parowanie próżniowe"
 pm_brine_electrolysis: "Elektroliza solanki"
 pmg_fertilizer_production: "Produkcja nawozu"
 pm_no_artificial_fertilizers: "Brak nawozów sztucznych"
 pm_artificial_fertilizers: "Nawozy sztuczne"
 pm_improved_fertilizer: "Nawozy zmodyfikowane"
 pm_nitrogen_fixation: "Proces wiązania azotu cząsteczkowego"
 pm_dyes_production: "Produkcja barwników"
 pm_no_synthetic_dyes: "Brak barwników syntetycznych"
 pmg_synthetic_dyes: "Barwniki syntetyczne"
 pm_silk_production: "Produkcja jedwabiu"
 pm_no_artificial_fibers: "Priorytetowa produkcja barwnika"
 pm_rayon: "Wiskoza"
 #Foundries
 pm_steamworks: "Metody oparte na wykorzystaniu pary"
 pm_no_artillery_production: "Priorytetowa produkcja broni krótkiej"
 pm_artillery_production: "Produkcja broni artyleryjskiej"
 #Motor Industries
 pmg_automobile_production: "Produkcja automobilów"
 pm_automobile_production: "Produkcja automobilów"
