l_braz_por:
 #DELETE:
 #pm_disabled_gin
 #pm_disabled_elastics
 #pm_masticators
 #pm_rubber_bands
 #pm_luxury_clothes
 #Agriculture Buildings
 pm_primary: "Primário"
 pmg_secondary_building_rye_farm: "Secundário"
 pmg_secondary_building_wheat_farm: "Secundário"
 pmg_secondary_building_rice_farm: "Secundário"
 pmg_secondary_building_maize_farm: "Secundário"
 pmg_secondary_building_millet_farm: "Secundário"
 pm_no_secondary: "Manter Monocultura"
 pm_potatoes: "Batatas"
 pm_vineyards: "Vinhedos"
 pm_vineyards_building_maize_farm: "Vinhedos"
 pm_apple_orchards: "Pomares de Maçãs"
 pm_citrus_orchards: "Pomares de Cítricos"
 pm_fig_orchards: "Pomares de Figos"
 pm_fig_orchards_building_rice_farm: "Pomares de Figos"
 pm_mulberry_groves: "Bosques de Amoras"
 pmg_automation: "Automação"
 pmg_automation_building_food_industry: "Automação"
 pmg_automation_building_textile_mills: "Automação"
 pmg_automation_building_furniture_manufacturies: "Automação"
 pmg_automation_building_tooling_workshops: "Automação"
 pmg_automation_building_paper_mills: "Automação"
 pmg_automation_building_steel_mills: "Automação"
 pmg_automation_building_motor_industry: "Automação"
 pmg_automation_building_automotive_industry: "$pmg_automation$"
 pm_civilian_priority: "Prioridade Civil"
 pm_military_priority: "Prioridade Militar"
 #Textile Mills
 pm_craftsman_sewing: "Costura Artesanal"
 pm_sewing_machines: "Máquinas de Costura"
 pm_electric_sewing_machines: "Máquinas de Costura Elétricas"
 pm_traditional_looms: "Teares Tradicionais"
 pm_mechanized_looms: "Teares Mecanizados"
 pm_automatic_power_looms: "Teares Mecânicos Automáticos"
 #Glassworks
 pm_leaded_glass: "Vidro de Chumbo"
 pm_manual_glassblowing: "Vidro Soprado Manualmente"
 #Chemical Plants
 pm_leblanc_process: "Processo Leblanc"
 pm_no_explosives_production: "Priorizar a Produção de Fertilizante"
 pm_ammonia-soda_process: "Processo Solvay"
 pm_vacuum_evaporation: "Evaporação a Vácuo"
 pm_brine_electrolysis: "Eletrólise da Salmoura"
 pmg_fertilizer_production: "Produção de Fertilizante"
 pm_no_artificial_fertilizers: "Nenhum Fertilizante Artificial"
 pm_artificial_fertilizers: "Fertilizantes Artificiais"
 pm_improved_fertilizer: "Fertilizantes Melhorados"
 pm_nitrogen_fixation: "Processo de Fixação de Nitrogênio"
 pm_dyes_production: "Produção de Tinturas"
 pm_no_synthetic_dyes: "Nenhuma Tintura Sintética"
 pmg_synthetic_dyes: "Tinturas Sintéticas"
 pm_silk_production: "Produção de Seda"
 pm_no_artificial_fibers: "Priorizar a Produção de Tintura"
 pm_rayon: "Rayon"
 #Foundries
 pm_steamworks: "A Vapor"
 pm_no_artillery_production: "Priorizar a Produção de Armas Leves"
 pm_artillery_production: "Produção de Artilharia"
 #Motor Industries
 pmg_automobile_production: "Produção de Automóveis"
 pm_automobile_production: "Produção de Automóveis"
 pm_mass_automobile_production: "Produção em Massa"
