l_turkish:
 SETTING_INPUT_CONTEXT_COMMON: "Yaygın"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Yaygın girdilerin tuş atamaları"
 SETTING_INPUT_ACTION_PAUSE: "Durdur / Devam Ettir"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Hızı Arttır"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Hızı Düşür"
 SETTING_INPUT_ACTION_SPEED_ONE: "1. Hız"
 SETTING_INPUT_ACTION_SPEED_TWO: "2. Hız"
 SETTING_INPUT_ACTION_SPEED_THREE: "3. Hız"
 SETTING_INPUT_ACTION_SPEED_FOUR: "4. Hız"
 SETTING_INPUT_ACTION_SPEED_FIVE: "5. Hız"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Müziği Çal/Duraksat"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Sonraki şarkı"
 SETTING_INPUT_ACTION_CAMERA_UP: "Kamerayı Yukarı Kaydır"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Kamerayı Sola Kaydır"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Kamerayı Aşağı Kaydır"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Kamerayı Sağa Kaydır"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Konum Bulucu"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Siyaset"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Bütçe"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Binalar"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Pazar"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Ordu"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Diplomatik"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Teknoloji"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "Topluluk"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Nüfus"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Günlük"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Ülkeler Bloku"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Şirketler"
 SETTING_INPUT_ACTION_MAP_LIST: "Defter"
 SETTING_INPUT_ACTION_BACK: "Geri"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Yan Bilgi"
 SETTING_INPUT_ACTION_TAB_1: "1. Sekme"
 SETTING_INPUT_ACTION_TAB_2: "2. Sekme"
 SETTING_INPUT_ACTION_TAB_3: "3. Sekme"
 SETTING_INPUT_ACTION_TAB_4: "4. Sekme"
 SETTING_INPUT_ACTION_TAB_5: "5. Sekme"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Üretim Görünümü"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Siyasi Görünüm"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Diplomatik Görünüm"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Askeri Görünüm"
 SETTING_INPUT_ACTION_TRADE_LENS: "Ticari Görünüm"
 SETTING_INPUT_ACTION_CONFIRM: "Onayla"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Mevcut Durum"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "İnşa Sırası"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "İnşa Sırasını Durdur/Devam Ettir"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Ayrıntılara Git"
 SETTING_INPUT_ACTION_SCROLL_UP: "Yukarı kaydır"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Aşağı kaydır"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Hata Ayıklama) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Yan Bilgide Sabitlenenleri Göster"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Yan Bilgide Ekonomiyi Göster"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Yan Bilgide Siyaseti Göster"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Yan Bilgide Diplomasiyi Göster"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Yan Bilgide Orduyu Göster"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Yan Bilgide Tümünü Göster"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Sabitle/Kaldır"
 SETTING_INPUT_ACTION_ZOOM_TO: "Yakınlaş:"
 SETTING_INPUT_ACTION_MERGE: "Birleştir"
 SETTING_INPUT_ACTION_COUNTRY_PANEL: "Ülke Ayrıntıları"
