l_turkish:
 #DELETE:
 #pm_disabled_gin
 #pm_disabled_elastics
 #pm_masticators
 #pm_rubber_bands
 #pm_luxury_clothes
 #Agriculture Buildings
 pm_primary: "Ana"
 pmg_secondary_building_rye_farm: "İkincil"
 pmg_secondary_building_wheat_farm: "İkincil"
 pmg_secondary_building_rice_farm: "İkincil"
 pmg_secondary_building_maize_farm: "İkincil"
 pmg_secondary_building_millet_farm: "İkincil"
 pm_no_secondary: "Tek Ürün Yetiştir"
 pm_potatoes: "Patates"
 pm_vineyards: "Üzüm Bağları"
 pm_vineyards_building_maize_farm: "Üzüm Bağları"
 pm_apple_orchards: "Elma Bahçeleri"
 pm_citrus_orchards: "Narenciye Bahçeleri"
 pm_fig_orchards: "İncir Bahçeleri"
 pm_fig_orchards_building_rice_farm: "İncir Bahçeleri"
 pm_mulberry_groves: "Dut Koruları"
 pmg_automation: "Otomasyon"
 pmg_automation_building_food_industry: "Otomasyon"
 pmg_automation_building_textile_mills: "Otomasyon"
 pmg_automation_building_furniture_manufacturies: "Otomasyon"
 pmg_automation_building_tooling_workshops: "Otomasyon"
 pmg_automation_building_paper_mills: "Otomasyon"
 pmg_automation_building_steel_mills: "Otomasyon"
 pmg_automation_building_motor_industry: "Otomasyon"
 pm_civilian_priority: "Sivil Öncelik"
 pm_military_priority: "Askeri Öncelik"
 #Textile Mills
 pm_craftsman_sewing: "El Dikişi"
 pm_sewing_machines: "Dikiş Makineleri"
 pm_electric_sewing_machines: "Elektrikli Dikiş Makineleri"
 pm_traditional_looms: "Geleneksel Dokuma Tezgâhları"
 pm_mechanized_looms: "Mekanize Dokuma Tezgâhları"
 pm_automatic_power_looms: "Otomatik Elektrikli Dokuma Tezgâhları"
 #Glassworks
 pm_leaded_glass: "Kristal Cam"
 pm_manual_glassblowing: "Elle Cam Üfleme"
 #Chemical Plants
 pm_leblanc_process: "Leblanc İşlemi"
 pm_no_explosives_production: "Gübre Üretimi Önceliği"
 pm_ammonia-soda_process: "Amonyak-soda İşlemi"
 pm_vacuum_evaporation: "Vakumlu Buharlaşma"
 pm_brine_electrolysis: "Tuzlu Su Elektrolizi"
 pmg_fertilizer_production: "Gübre Üretimi"
 pm_no_artificial_fertilizers: "Suni Gübre Yok"
 pm_artificial_fertilizers: "Suni Gübreler"
 pm_improved_fertilizer: "Geliştirilmiş Gübreler"
 pm_nitrogen_fixation: "Azot Bağlama İşlemi"
 pm_dyes_production: "Boya Üretimi"
 pm_no_synthetic_dyes: "Sentetik Boya Yok"
 pmg_synthetic_dyes: "Sentetik Boya"
 pm_silk_production: "İpek Üretimi"
 pm_no_artificial_fibers: "Boya Üretimi Önceliği"
 pm_rayon: "Rayon"
 #Foundries
 pm_steamworks: "Buharlı Makineler"
 pm_no_artillery_production: "Hafif Silah Üretimi Önceliği"
 pm_artillery_production: "Top Üretimi"
 #Motor Industries
 pmg_automobile_production: "Otomobil Üretimi"
 pm_automobile_production: "Otomobil Üretimi"
