l_french:
 SETTING_INPUT_CONTEXT_COMMON: "Commun"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Raccourcis clavier pour le contexte d’entrée commun"
 SETTING_INPUT_ACTION_PAUSE: "Pause / Reprendre"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Augmenter la vitesse"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Diminuer la vitesse"
 SETTING_INPUT_ACTION_SPEED_ONE: "Vitesse 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "Vitesse 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "Vitesse 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "Vitesse 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "Vitesse 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Lire/mettre en pause la musique"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Piste musicale suivante"
 SETTING_INPUT_ACTION_CAMERA_UP: "Panoramique vers le haut"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Panoramique vers la gauche"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Panoramique vers le bas"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Panoramique vers la droite"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Recherche de lieux"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Politique"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Budget"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Bâtiments"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Marché"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Militaire"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Diplomatique"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Technologie"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "Société"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Population"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Journal"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Bloc de nations"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Compagnies"
 SETTING_INPUT_ACTION_MAP_LIST: "Registre"
 SETTING_INPUT_ACTION_BACK: "Retour"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Tableau de bord"
 SETTING_INPUT_ACTION_TAB_1: "Onglet 1"
 SETTING_INPUT_ACTION_TAB_2: "Onglet 2"
 SETTING_INPUT_ACTION_TAB_3: "Onglet 3"
 SETTING_INPUT_ACTION_TAB_4: "Onglet 4"
 SETTING_INPUT_ACTION_TAB_5: "Onglet 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Aperçu de la production"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Aperçu politique"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Aperçu diplomatique"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Aperçu militaire"
 SETTING_INPUT_ACTION_TRADE_LENS: "Aperçu du commerce"
 SETTING_INPUT_ACTION_CONFIRM: "Confirmer"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Situation actuelle"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "File d’attente de construction"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "Mettre en pause/Rétablir la file d’attente de construction"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Aller à l’écran Détails"
 SETTING_INPUT_ACTION_SCROLL_UP: "Faire défiler vers le haut"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Faire défiler vers le bas"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Afficher Épinglés au tableau de bord"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Afficher Économie au tableau de bord"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Afficher Politique au tableau de bord"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Afficher Diplomatie au tableau de bord"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Afficher Militaire au tableau de bord"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Afficher Tout au tableau de bord"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Activer/Désactiver l'épingle"
 SETTING_INPUT_ACTION_ZOOM_TO: "Zoomer"
 SETTING_INPUT_ACTION_MERGE: "Fusionner"
 SETTING_INPUT_ACTION_COUNTRY_PANEL: "Détails du pays"
