l_french:
 #DELETE:
 #pm_disabled_gin
 #pm_disabled_elastics
 #pm_masticators
 #pm_rubber_bands
 #pm_luxury_clothes
 #Agriculture Buildings
 pm_primary: "Principale"
 pmg_secondary_building_rye_farm: "Secondaire"
 pmg_secondary_building_wheat_farm: "Secondaire"
 pmg_secondary_building_rice_farm: "Secondaire"
 pmg_secondary_building_maize_farm: "Secondaire"
 pmg_secondary_building_millet_farm: "Secondaire"
 pm_no_secondary: "Maintien d’une culture unique"
 pm_potatoes: "Pommes de terre"
 pm_vineyards: "Vignobles"
 pm_vineyards_building_maize_farm: "Vignobles"
 pm_apple_orchards: "Pommeraies"
 pm_citrus_orchards: "Plantations d’agrumes"
 pm_fig_orchards: "Figueraies"
 pm_fig_orchards_building_rice_farm: "Figueraies"
 pm_mulberry_groves: "Mûreraies"
 pmg_automation: "Automatisation"
 pmg_automation_building_food_industry: "Automatisation"
 pmg_automation_building_textile_mills: "Automatisation"
 pmg_automation_building_furniture_manufacturies: "Automatisation"
 pmg_automation_building_tooling_workshops: "Automatisation"
 pmg_automation_building_paper_mills: "Automatisation"
 pmg_automation_building_steel_mills: "Automatisation"
 pmg_automation_building_motor_industry: "Automatisation"
 pmg_automation_building_automotive_industry: "$pmg_automation$"
 pm_civilian_priority: "Priorité civile"
 pm_military_priority: "Priorité militaire"
 #Textile Mills
 pm_craftsman_sewing: "Couture artisanale"
 pm_sewing_machines: "Machines à coudre"
 pm_electric_sewing_machines: "Machines à coudre électriques"
 pm_traditional_looms: "Métiers à tisser traditionnels"
 pm_mechanized_looms: "Métiers à tisser mécanisés"
 pm_automatic_power_looms: "Métiers à tisser mécaniques automatiques"
 #Glassworks
 pm_leaded_glass: "Verre plombé"
 pm_manual_glassblowing: "Soufflage du verre artisanal"
 #Chemical Plants
 pm_leblanc_process: "Procédé Leblanc"
 pm_no_explosives_production: "Prioriser la production d’engrais"
 pm_ammonia-soda_process: "Procédé Solvay"
 pm_vacuum_evaporation: "Évaporation sous vide"
 pm_brine_electrolysis: "Électrolyse de saumure"
 pmg_fertilizer_production: "Production d’engrais"
 pm_no_artificial_fertilizers: "Aucun engrais artificiel"
 pm_artificial_fertilizers: "Engrais artificiels"
 pm_improved_fertilizer: "Engrais améliorés"
 pm_nitrogen_fixation: "Procédé de fixation de l’azote"
 pm_dyes_production: "Production de colorants"
 pm_no_synthetic_dyes: "Aucun colorant synthétique"
 pmg_synthetic_dyes: "Colorants synthétiques"
 pm_silk_production: "Production de soie"
 pm_no_artificial_fibers: "Prioriser la production de colorants"
 pm_rayon: "Soie artificielle"
 #Foundries
 pm_steamworks: "Machines à vapeur"
 pm_no_artillery_production: "Prioriser la production d’armes légères"
 pm_artillery_production: "Production d’artillerie"
 #Motor Industries
 pmg_automobile_production: "Production automobile"
 pm_automobile_production: "Production automobile"
 pm_mass_automobile_production: "Production de masse"
