l_german:
 #DELETE:
 #pm_disabled_gin
 #pm_disabled_elastics
 #pm_masticators
 #pm_rubber_bands
 #pm_luxury_clothes
 #Agriculture Buildings
 pm_primary: "Primär"
 pmg_secondary_building_rye_farm: "Sekundär"
 pmg_secondary_building_wheat_farm: "Sekundär"
 pmg_secondary_building_rice_farm: "Sekundär"
 pmg_secondary_building_maize_farm: "Sekundär"
 pmg_secondary_building_millet_farm: "Sekundär"
 pm_no_secondary: "Gleichbleibende Feldfrucht behalten"
 pm_potatoes: "Kartoffeln"
 pm_vineyards: "Weinberge"
 pm_vineyards_building_maize_farm: "Weinberge"
 pm_apple_orchards: "Apfelhaine"
 pm_citrus_orchards: "Zitrushaine"
 pm_fig_orchards: "Feigenhaine"
 pm_fig_orchards_building_rice_farm: "Feigenhaine"
 pm_mulberry_groves: "Maulbeerhaine"
 pmg_automation: "Automation"
 pmg_automation_building_food_industry: "Automation"
 pmg_automation_building_textile_mills: "Automation"
 pmg_automation_building_furniture_manufacturies: "Automation"
 pmg_automation_building_tooling_workshops: "Automation"
 pmg_automation_building_paper_mills: "Automation"
 pmg_automation_building_steel_mills: "Automation"
 pmg_automation_building_motor_industry: "Automation"
 pmg_automation_building_automotive_industry: "$pmg_automation$"
 pm_civilian_priority: "Zivilpriorität"
 pm_military_priority: "Militärpriorität"
 #Textile Mills
 pm_craftsman_sewing: "Handnäharbeit"
 pm_sewing_machines: "Nähmaschinen"
 pm_electric_sewing_machines: "Elektrische Nähmaschinen"
 pm_traditional_looms: "Traditionelle Webstühle"
 pm_mechanized_looms: "Webmaschinen"
 pm_automatic_power_looms: "Automatische Webmaschinen"
 #Glassworks
 pm_leaded_glass: "Bleiglas"
 pm_manual_glassblowing: "Manuelle Glasbläser"
 #Chemical Plants
 pm_leblanc_process: "Leblanc-Verfahren"
 pm_no_explosives_production: "Vorrang für Düngerproduktion"
 pm_ammonia-soda_process: "Ammoniak-Soda-Verfahren"
 pm_vacuum_evaporation: "Vakuumverdampfung"
 pm_brine_electrolysis: "Salzwasser-Elektrolyse"
 pmg_fertilizer_production: "Düngerproduktion"
 pm_no_artificial_fertilizers: "Kein Kunstdünger"
 pm_artificial_fertilizers: "Kunstdünger"
 pm_improved_fertilizer: "Verbesserter Dünger"
 pm_nitrogen_fixation: "Stickstofffixierungsverfahren"
 pm_dyes_production: "Färbemittel-Produktion"
 pm_no_synthetic_dyes: "Keine synthetischen Färbemittel"
 pmg_synthetic_dyes: "Synthetische Färbemittel"
 pm_silk_production: "Seiden-Produktion"
 pm_no_artificial_fibers: "Vorrang für Färbemittel-Produktion"
 pm_rayon: "Rayon"
 #Foundries
 pm_steamworks: "Dampfwerke"
 pm_no_artillery_production: "Vorrang für Handfeuerwaffen-Produktion"
 pm_artillery_production: "Artillerie-Produktion"
 #Motor Industries
 pmg_automobile_production: "Automobil-Produktion"
 pm_automobile_production: "Automobil-Produktion"
 pm_mass_automobile_production: "Massenproduktion"
