l_spanish:
 #DELETE:
 #pm_disabled_gin
 #pm_disabled_elastics
 #pm_masticators
 #pm_rubber_bands
 #pm_luxury_clothes
 #Agriculture Buildings
 pm_primary: "Principal"
 pmg_secondary_building_rye_farm: "Secundario"
 pmg_secondary_building_wheat_farm: "Secundario"
 pmg_secondary_building_rice_farm: "Secundario"
 pmg_secondary_building_maize_farm: "Secundario"
 pmg_secondary_building_millet_farm: "Secundario"
 pm_no_secondary: "Mantener monocultivo"
 pm_potatoes: "Patatas"
 pm_vineyards: "Viñedos"
 pm_vineyards_building_maize_farm: "Viñedos"
 pm_apple_orchards: "Manzanares"
 pm_citrus_orchards: "Naranjales"
 pm_fig_orchards: "Higuerales"
 pm_fig_orchards_building_rice_farm: "Higuerales"
 pm_mulberry_groves: "Morerales"
 pmg_automation: "Automatización"
 pmg_automation_building_food_industry: "Automatización"
 pmg_automation_building_textile_mills: "Automatización"
 pmg_automation_building_furniture_manufacturies: "Automatización"
 pmg_automation_building_tooling_workshops: "Automatización"
 pmg_automation_building_paper_mills: "Automatización"
 pmg_automation_building_steel_mills: "Automatización"
 pmg_automation_building_motor_industry: "Automatización"
 pmg_automation_building_automotive_industry: "$pmg_automation$"
 pm_civilian_priority: "Prioridad civil"
 pm_military_priority: "Prioridad militar"
 #Textile Mills
 pm_craftsman_sewing: "Costura artesanal"
 pm_sewing_machines: "Máquinas de coser"
 pm_electric_sewing_machines: "Máquinas de coser eléctricas"
 pm_traditional_looms: "Telares tradicionales"
 pm_mechanized_looms: "Telares mecanizados"
 pm_automatic_power_looms: "Telares eléctricos automáticos"
 #Glassworks
 pm_leaded_glass: "Vidrio emplomado"
 pm_manual_glassblowing: "Soplado de vidrio manual"
 #Chemical Plants
 pm_leblanc_process: "Proceso Leblanc"
 pm_no_explosives_production: "Priorizar producción de fertilizante"
 pm_ammonia-soda_process: "Proceso Solvay"
 pm_vacuum_evaporation: "Evaporación al vacío"
 pm_brine_electrolysis: "Electrólisis de salmuera"
 pmg_fertilizer_production: "Producción de fertilizantes"
 pm_no_artificial_fertilizers: "Sin fertilizantes artificiales"
 pm_artificial_fertilizers: "Fertilizantes artificiales"
 pm_improved_fertilizer: "Fertilizantes mejorados"
 pm_nitrogen_fixation: "Proceso de fijación de nitrógeno"
 pm_dyes_production: "Producción de tintes"
 pm_no_synthetic_dyes: "Sin tintes sintéticos"
 pmg_synthetic_dyes: "Tintes sintéticos"
 pm_silk_production: "Producción de seda"
 pm_no_artificial_fibers: "Priorizar producción de tintes"
 pm_rayon: "Rayón"
 #Foundries
 pm_steamworks: "Talleres con vapor"
 pm_no_artillery_production: "Priorizar producción de armas pequeñas"
 pm_artillery_production: "Producción de artillería"
 #Motor Industries
 pmg_automobile_production: "Producción de automóviles"
 pm_automobile_production: "Producción de automóviles"
 pm_mass_automobile_production: "Producción en serie"
